### ISSUE TITLE
Link broken ? 

### ISSUE THREAD

**Issue by Wotn9** [aMediocreDad/jal#6]
![image](https://user-images.githubusercontent.com/45216414/166136344-04d6d676-116f-476f-998b-d89a3617213c.png)

**Comment by aMediocreDad** [comment]
You'll have to be more specific than that. What exactly is the issue?

**Comment by farling42** [comment]
The modules listing in the foundry modules list is now only showing a "Path:" to a local directory. There is no URL entry like for the other installed modules.

I don't know if this is caused by the change to show version 9 removed the quotes around the digit 9. I still use quotes around the 9 in my module.json

**Comment by aMediocreDad** [comment]
Could be. Absolutely hate the confusion "v9", 9, "9" has created for me. I need to go look for an official source on this.

**Comment by aMediocreDad** [comment]
I have tested in a clean Foundry installation updating from 2.0.0 to 3.0.1. And I do not see any issues with updating. Yes, the module does not have the URL listed, but it has never had the URL listed. I will go ahead and add it in an update. 

That said, I am not sure that is what this issue is about?

**Comment by farling42** [comment]
The original picture shows the change of version, but for all other modules being updated, the change of version appears as a clickable link.
For this module, there is no clickable link.
This is a useful feature for people to be able to see what has changed in each module that is being updated.

**Comment by aMediocreDad** [comment]
Thank you. I was not aware of that feature. I am also not entirely certain what is required for that feature to function.

**Comment by aMediocreDad** [comment]
This should be solved by now.
